### PR TITLE
Trawl tension measurement

### PR DESCRIPTION
**Pull request by DujardinGijs**

### CODE REVIEW

**Comment by Qwerios** [comment]
Thank you for your contribution and interest in PoseiDAT @DujardinGijs 

So far we've kept measurements more generic. From a data perspective this is more flexible and future proof but might be a bit more cumbersome to consume. All the values in the proposed schema are numerics so they could in theorie be added to a PoseiDAT journal as individual measurements provided we add them to the `core/enum/measurement-type.json`.

@daanpape could you weigh in on this in regards to the measurement data your are modelling. Have you already looked at trawl tension? I'm not opposed to a more specialised structure for complex data and this does look wel thought out. Perhaps you could add the equivalent example using current measurement objects.

**Comment by daanpape** [comment]
@Qwerios for your info, @DujardinGijs is our engineer who is now expanding the uplink from the concentrator and thus also the PoseiDAT format. There was an internal discussion about the fact if we would split up the trawl tension into seperate measurements or to create a single structure.

We have opted for the single structure because the measurements are inherently connected together and meaningless as separate values. To clarify: when you measure trawl tension at port you must know the value at starboard at the exact same time to interpret the data. When we would split up the measurements of a trawl tension device it would be as if we would split up a GPS position with a separate latitude and longitude measurement.

**Comment by Qwerios** [comment]
Could you please supply a description for the PR next time then so I am aware of the source of this change. Seeing as how this is a public repository and I didn't know Gijs yet (nice to meet you!) it could have come from everywhere.

Your reasoning seems sound to me I'll see about merging this today

**Comment by Qwerios** [comment]
@DujardinGijs since you are still pushing changes can you let me know when you consider this done so I can see about merging it. Also it would be great if you could add a unit test with an example when it's complete

**Comment by DujardinGijs** [comment]
@Qwerios nice to meet u too, I have revert the scale measurement commit for an other pull request, i am currently adding some unit test and will let u know when its finished

**Comment by DujardinGijs** [comment]
@Qwerios I have added unit tests for the device measurements and the trawl tension measurement should be completed now and ready to merge

**Review by daanpape — COMMENTED** [review]
This looks ok for me.

**Pull request merged**
