### PR TITLE
feat(ais): added ais messages and ais entry 

### PR DESCRIPTION
**Pull request by Nielsien**
In this pull request I created a new entry for AIS messages and the first schema for such a message.

But before I want to add all the other message schema's I wanted to discuss the preferred way of handling such an entry.
So this pull request does not need to merged yet, since I'll add more message schema's after this.

The way I did it in this pr is that an AIS message has a `AisMessageEntry` which is very similar to the `DeviceMeasurementEntry`.
In this case each entry has his message object which contains the required properties for each message with all the schemas in seperate objects.

So another way to do this is to implement the AIS messages in the `device-measurement.json`, since these have almost the same construct apart from the value.

Like so (in `device-measurement.json`):
```
"properties": {
    "entry_type": {
      "description": "The journal entry type identifer",
      "type": "string",
      "enum": [
        "device-measurement"
      ],
      "default": "device-measurement"
    },
    "device_id": {
      "type": "string",
      "description": "The unique identifier for the device"
    },
    "value": {
      "description": "The registered measurement for the device",
      "$ref": "https://poseidat.org/schema/core/measurement/measurement-value.json"
    },
    "ais_message": {
      "description": "The message send by the AIS device",
      "$ref": "https://poseidat.org/schema/core/ais-message/ais-message.json"
    }
  },
  "oneOf": [
    {  "required": [ "entry_type", "device_id", "value" ]},
    {  "required": [ "entry_type", "device_id", "ais_message"]}
  ],
```

In this case the ais gets sent like a measurement from a device.

Another way to do it is use the `entry_type` setup where we have a entry for each AIS message type.
So for example `entry-ais-position-report.ts` where the entry_type decides which schema to use.

### CODE REVIEW

**Comment by Qwerios** [comment]
Looking at the structure and trying to understand it. What would make sense to me would be to:

* create an AIS message entry type in `/src/entry/ais-message.json`
* for each message type a schema can be added in `/src/core/ais-message/xyz.json`
* every AIS message entry has an `allOf` include of `/src/core/ais-message/base-message.json` which has the shared properties
* the base message will have an `ais_message_type` which is the string enum with the known types
* Inside the specific entries the `ais_message_type` property will fixate the enum to a single value

So much like a measurement entry an AIS message can be added to the journal and the contents will further specify what type it is.

**Comment by Nielsien** [comment]
Thanks again! When I have time this week I'll finish the schemas

**Comment by Nielsien** [comment]
Found some time to finish this pr

**Comment by Qwerios** [comment]
Closing this PR due to age. Please re-open if needed

**Pull request closed without merging**
