### PR TITLE
Feature/fish type as string

### PR DESCRIPTION
**Pull request by Qwerios**
Managing fish types involves a lot of data which differs per fishing method, target ERS country, etc. 
Our reference list contains well over 3000 codes in a managed system. Turning them into a flat enum and continuous updates does not seem sensible.

The pattern for a specie code is still enforced this way while leaving the code selection to the client application and/or server

### CODE REVIEW

**Comment by daanpape** [comment]
I absolutely agree on this, it offers a more flexible way to define fish species.

**Comment by Qwerios** [comment]
Released as version v0.0.10

**Comment by JensPauwels** [comment]
@Qwerios As mentioned in the email it is also important to not forget to push this release to the npm repo. This ensures us that we can implement the new feature on our side.

**Comment by Qwerios** [comment]
@JensPauwels I beat your question by 15 seconds

**Pull request merged**
